<a href="https://colab.research.google.com/github/Putranto13/Tugas_Machine_Learning/blob/main/Week9_3_3_Concise_Implementation_of_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install d2l==0.17.0

     |████████████████████████████████| 83 kB 1.2 MB/s 


In [3]:
import numpy as np
import tensorflow as tf
from d2l import tensorflow as d2l

true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [4]:
def load_array(data_arrays, batch_size, is_train=True):  #@save
    """Construct a TensorFlow data iterator."""
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [5]:
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[ 0.6089924 ,  0.00955104],
        [-0.23191585, -0.825474  ],
        [-1.1047477 , -1.4861735 ],
        [ 0.13415499,  0.6041663 ],
        [-1.588182  ,  0.07377202],
        [ 2.3120956 ,  0.36828938],
        [ 1.9670881 , -0.32568434],
        [-0.13928564, -0.07016194],
        [-0.07502973, -0.5083383 ],
        [ 1.9756621 ,  0.7519315 ]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[5.3849187],
        [6.5393276],
        [7.0194817],
        [2.4105208],
        [0.7659141],
        [7.5662985],
        [9.247559 ],
        [4.162594 ],
        [5.782188 ],
        [5.585285 ]], dtype=float32)>)

In [6]:
# `keras` is the high-level API for TensorFlow
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))

In [7]:
initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))

In [8]:
loss = tf.keras.losses.MeanSquaredError()

In [9]:
trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

In [10]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training=True), y)
        grads = tape.gradient(l, net.trainable_variables)
        trainer.apply_gradients(zip(grads, net.trainable_variables))
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000244
epoch 2, loss 0.000105
epoch 3, loss 0.000104


In [11]:
w = net.get_weights()[0]
print('error in estimating w', true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print('error in estimating b', true_b - b)

error in estimating w tf.Tensor([-6.3705444e-04  1.2874603e-05], shape=(2,), dtype=float32)
error in estimating b [-3.194809e-05]
